# Generated by Django 2.2.11 on 2021-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20210117_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, null=True, unique=True),
        ),
    ]
