# Generated by Django 2.2.11 on 2021-01-23 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20210118_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=user_app.models.FixedCharField(db_index=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_nick',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('focus_id', models.AutoField(primary_key=True, serialize=False)),
                ('focus_time', models.DateTimeField(auto_now_add=True)),
                ('be_focus_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('focus_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='focus',
            field=models.ManyToManyField(through='user_app.Focus', to=settings.AUTH_USER_MODEL),
        ),
    ]
