# Generated by Django 2.2.11 on 2021-01-24 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20210124_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='be_focus_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_me_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='focus',
            name='focus_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
