# Generated by Django 2.2.11 on 2021-03-07 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20210128_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('sex', models.BooleanField(default=True)),
                ('birthday', models.DateField(default='2010-01-01')),
                ('hometown', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='detail_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.UserDetailInfo'),
        ),
    ]
