# Generated by Django 2.2.11 on 2021-03-07 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20210307_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='detail_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.UserDetailInfo'),
            preserve_default=False,
        ),
    ]
