# Generated by Django 2.2.11 on 2021-02-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210129_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
