# Generated by Django 2.2.11 on 2021-03-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_blog_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
